.TH "PDIR" "1" "August 21, 2019" "" "User Commands"

.SH NAME
pdir \-list directory contents

.SH SYNOPSIS
.B pdir
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...

.SH DESCRIPTION
\fBpdir\fR is referenced \fBls\fR (GNU Core Utilities).
.PP
List information about the FILEs (the current directory by default).

.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-all\fR
do not ignore entries starting with .
.TP
\fB\-A\fR, \fB\-\-almost\-all\fR
do not list implied . and ..
.TP
\fB\-l\fR
use a long listing format
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit

.SH AUTHOR
Written by LeavaTail <starbow.duster@gmail.com>.

.SH "SEE ALSO"
\fBls\fR(1)
